module_chat = "Chat"
mt_chat_shout = "Shout"
md_chat_shout = "Send a message to all channels on all servers. The origin server sets the price in credits."
cfg_price = "Method price (credits)"
cfg_shout_show_sender = "Show shout sender"
cfg_shout_allow_anon = "Allow anonymous shouts"
err_shout_anon_disabled = "Anonymous shouts are disabled."
msg_shout_sent = "Shout sent to %s channels across all servers."
msg_global_message_sent = "Global message sent to %s channels."
